package Core;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ActorComponent.java
//  @ Date : 17.05.2014
//  @ Author : 
//
//




public class ActorComponent extends Component {
	public ActorComponent(String id)
	{
		this.setId(id);
	}

	public ActorComponent() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
}
