package Core;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ComplexComponent.java
//  @ Date : 17.05.2014
//  @ Author : 
//
//




public class ComplexComponent extends ActorComponent {

	public ComplexComponent() {
		super();
		// TODO Auto-generated constructor stub
	}

	public ComplexComponent(String id) {
		super(id);
		// TODO Auto-generated constructor stub
	}
	
}
