package Core;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConsumingPort.java
//  @ Date : 17.05.2014
//  @ Author : 
//
//




public class ConsumingPort extends Port {
	private ActorComponent myComponent;
	
	public ConsumingPort(String id, ActorComponent c) {
		super(id);
		myComponent = c;
	}
	
	public void registerActorComponent(ActorComponent component) {
		myComponent = component;
	}
	
	public void unregisterActorComponent() {
		myComponent = null;
	}
	
	public ActorComponent getActorComponent() {
		return myComponent;
	}
	
	public void tellState() {
		if(myComponent != null) myComponent.exec();
	}

	@Override
	public void setState(Boolean state) {
		super.setState(state);
		tellState();
	}
	
	
}
