package Core;

import java.io.FileNotFoundException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenceHandler.java
//  @ Date : 19.05.2014
//  @ Author : 
//
//




public interface PersistenceHandler {
	public void saveConfiguration(String confFile, Manager manager) throws Exception;
	public void loadConfiguration(String confFile, Manager manager) throws Exception;
}
