package Core;

import org.eclipse.swt.widgets.Display;

import GUI.GUI_Port;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Port.java
//  @ Date : 17.05.2014
//  @ Author : 
//
//




public class Port {
	private String id;
	protected Boolean state;
	public GUI_Port myGUI;
	protected Runnable r;
	
	public Port(String id)
	{
		this.id = id;
		this.state = false;
		final Port me = this;
		
		r = new Runnable() {

			@Override
			public void run() {
				myGUI.updateGUI(me);
				
			}
			
		};
	}
	
	public GUI_Port getMyGUI() {
		return myGUI;
	}

	public void setMyGUI(GUI_Port myGUI) {
		this.myGUI = myGUI;
	}
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public Boolean getState() {
		return state;
	}
	public void setState(Boolean state) {
		this.state = state;
		if(myGUI != null) Display.getDefault().syncExec(r);
	}
	@Override
	public String toString() {
		return id;
	}
	
}
