package Core;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProducingPort.java
//  @ Date : 17.05.2014
//  @ Author : 
//
//




public class ProducingPort extends Port {
	
	private List<ConsumingPort> consumingPorts;
	
	public ProducingPort(String id) {
		super(id);
		consumingPorts = new ArrayList<ConsumingPort>();
	}

	public void registerConsumingPort(ConsumingPort port) {
		consumingPorts.add(port);
	}
	
	public void unregisterConsumingPort(ConsumingPort port) {
		if(getMyGUI() != null) getMyGUI().getMyGUIComponent().removeRelation(this, port);
		consumingPorts.remove(port);
	}
	
	public void tellState() {
		for(ConsumingPort p: consumingPorts)
		{
			p.setState(this.getState());
		}
	}

	public List<ConsumingPort> getConsumingPorts() {
		return consumingPorts;
	}

	public void setConsumingPorts(List<ConsumingPort> consumingPorts) {
		this.consumingPorts = consumingPorts;
	}

	@Override
	public void setState(Boolean state) {
		if(state != this.state)	super.setState(state);
		this.tellState();
	}
	
}
