package Core;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SecurityComponent.java
//  @ Date : 17.05.2014
//  @ Author : 
//
//

public class SecurityComponent extends ActorComponent{
	
	public String PORT_SECURITY_STOP = "SecurityStop";
	public String PORT_SECURITY_RESTART = "SecurityRestart";
	
	public SecurityComponent() {
		super();
		// TODO Auto-generated constructor stub
	}

	public SecurityComponent(String id) {
		super(id);
		
	}
	
	public void init(){
		this.addPort(new ConsumingPort("SecurityStop", this));
		this.addPort(new ConsumingPort("SecurityRestart", this));
	}
	
	public void exec(){
		if(getPort("SecurityStop").getState())
		{
			Manager.getInstance().SecurityStop();
		}
		
		if(getPort("SecurityRestart").getState())
		{
			Manager.getInstance().SecurityRestart();
		}
	}
	
}
