package Core;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SensorComponent.java
//  @ Date : 17.05.2014
//  @ Author : 
//
//




public class SensorComponent extends Component {
	public SensorComponent() {
		super();
		// TODO Auto-generated constructor stub
	}

	public SensorComponent(String id)
	{
		this.setId(id);
	}
}
